### ISSUE TITLE
Question: What is the status of this Repo?

### ISSUE THREAD

**Issue by DerekChasse** [BlazorExtensions/Blazor.Extensions.OfficeUIFabric#2]
There is a lot of promise in this repo, however it looks like it is very early in it's development.

Has this repo stalled? There haven't been any commits in the past 6 months at time of writing.

The only components that I see [implemented](https://github.com/BlazorExtensions/BlazorOfficeUIFabric/tree/master/src/Blazor.OfficeUiFabric/Components) are Buttons, Icons and Images.  There are ton [more](https://developer.microsoft.com/en-us/fabric#/components), and I'm not at all expecting them to all be implemented while Blazor is still experimental but I'm curious as to whether or not I am looking in the right spot.

Are there examples of the usage of these components?

**Comment by galvesribeiro** [comment]
Hello @DerekChasse 

The person who asked to create this repo and migrate the content is probably out of time to maintain it.

However, since now a lot changed on both OfficeUI and the new Microsoft Design language, I'll get back and review it once I get back to vacation later this month.

Please keep tuned on other issues so you can grab more updates soon.

Thanks!
